/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './pages/__root'
import { Route as IndexRouteImport } from './pages/index'

const UlasanIndexLazyRouteImport = createFileRoute('/ulasan/')()
const TentangIndexLazyRouteImport = createFileRoute('/tentang/')()
const ProductIndexLazyRouteImport = createFileRoute('/product/')()
const KeranjangIndexLazyRouteImport = createFileRoute('/keranjang/')()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UlasanIndexLazyRoute = UlasanIndexLazyRouteImport.update({
  id: '/ulasan/',
  path: '/ulasan/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./pages/ulasan/index.lazy').then((d) => d.Route))
const TentangIndexLazyRoute = TentangIndexLazyRouteImport.update({
  id: '/tentang/',
  path: '/tentang/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./pages/tentang/index.lazy').then((d) => d.Route))
const ProductIndexLazyRoute = ProductIndexLazyRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./pages/product/index.lazy').then((d) => d.Route))
const KeranjangIndexLazyRoute = KeranjangIndexLazyRouteImport.update({
  id: '/keranjang/',
  path: '/keranjang/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./pages/keranjang/index.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/keranjang': typeof KeranjangIndexLazyRoute
  '/product': typeof ProductIndexLazyRoute
  '/tentang': typeof TentangIndexLazyRoute
  '/ulasan': typeof UlasanIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/keranjang': typeof KeranjangIndexLazyRoute
  '/product': typeof ProductIndexLazyRoute
  '/tentang': typeof TentangIndexLazyRoute
  '/ulasan': typeof UlasanIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/keranjang/': typeof KeranjangIndexLazyRoute
  '/product/': typeof ProductIndexLazyRoute
  '/tentang/': typeof TentangIndexLazyRoute
  '/ulasan/': typeof UlasanIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/keranjang' | '/product' | '/tentang' | '/ulasan'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/keranjang' | '/product' | '/tentang' | '/ulasan'
  id: '__root__' | '/' | '/keranjang/' | '/product/' | '/tentang/' | '/ulasan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KeranjangIndexLazyRoute: typeof KeranjangIndexLazyRoute
  ProductIndexLazyRoute: typeof ProductIndexLazyRoute
  TentangIndexLazyRoute: typeof TentangIndexLazyRoute
  UlasanIndexLazyRoute: typeof UlasanIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ulasan/': {
      id: '/ulasan/'
      path: '/ulasan'
      fullPath: '/ulasan'
      preLoaderRoute: typeof UlasanIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang/': {
      id: '/tentang/'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/': {
      id: '/product/'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keranjang/': {
      id: '/keranjang/'
      path: '/keranjang'
      fullPath: '/keranjang'
      preLoaderRoute: typeof KeranjangIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KeranjangIndexLazyRoute: KeranjangIndexLazyRoute,
  ProductIndexLazyRoute: ProductIndexLazyRoute,
  TentangIndexLazyRoute: TentangIndexLazyRoute,
  UlasanIndexLazyRoute: UlasanIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
